config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'pages#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users

  resources :restaurants

  resources :polls do
    resources :poll_responses, only: [:create, :index]
    resources :orders, only: [:create, :index, :show]
  end


end

app/controllers/poll_responses_controller.rb
class PollResponsesController < ApplicationController
  before_action :set_poll

  def create
    @poll_response = @poll.poll_responses.new(poll_response_params)
    @poll_response.user = current_user
    if @poll_response.save
      redirect_to poll_poll_responses_path(@poll), notice: "Your vote has been recorded"
    else
      redirect_back fallback_location: @poll, alert: "Something went wrong: #{@poll_response.errors.full_messages.join(', ')}"
    end
  end

  def index
    respond_to do |format|
      format.html do
        @restaurants = @poll.restaurants
        @order = Order.new
      end

      @results  = PollResponse.where(poll: @poll).group_by do |response|
                    response.restaurant.name
                  end.transform_values{ |v| v.count }

      format.json do
        render json: @results
      end
    end
  end

  private

  def set_poll
    @poll = Poll.find(params[:poll_id])
  end

  def poll_response_params
    params.require(:poll_response).permit(:restaurant_id)
  end

end

app/views/poll_responses/index.html.erb
<%if current_user.admin? %>
  <h1 class="buffer">Waiting for votes...</h1>
  <div class="lds-ring"><div></div><div></div><div></div><div></div></div>
  <%= image_tag 'WhereTo_Icon.svg', class:"logo-icon animated fadeIn" %>
  <% if DateTime.now > @poll.end_time %>
    <%= controller.redirect_to poll_orders_path(@poll) %>
  <% end %>
<% else %>
  <% if @poll.closed? && @poll.winner %>
  <span class="chart"><%= pie_chart @results, refresh: 10 %></span>
    <h3 class="text-center winner"><%= @poll.winner.name %> is the winner!</h3>
    <h4 class="text-center dish">What would you like to eat?</h4>

    <%= form_with(model: [@poll, @order]) do |form| %>
      <% @poll.winner.dishes.each do |dish|%>
        <div class="btn-group dish-container" data-toggle="buttons"">
          <%= form.label(dish.name) do %>
            <div class="dish-list">
              <span class="poll-venue-name"><%= dish.name %></span>
              <%= form.radio_button(:dish_id, dish.id, checked: false, class:"form-radio") %>
            </div>
          <% end %>
        </div>
        <hr class="vote-hr">
        </div>
      <% end %>
      <div class="vote-submit">
        <%= form.submit "Order!", class: "btn btn-outline-secondary waves-effect vote-button" %>
      </div>
    <% end %>
  <% end %>
<% end %>