config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'pages#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users

  resources :restaurants

  resources :polls do
    resources :poll_responses, only: [:create, :index]
    resources :orders, only: [:create, :index, :show]
  end


end

app/models/poll.rb
class Poll < ApplicationRecord
  before_create :set_poll_end_time

  belongs_to :user
  has_many :restaurant_polls, dependent: :destroy
  has_many :restaurants, :through => :restaurant_polls
  has_many :dishes, :through => :restaurant_polls
  has_many :poll_responses, dependent: :destroy
  has_many :orders

  def set_poll_end_time
    self.end_time = DateTime.now + 90.seconds
  end

  def winner
    if closed? && poll_responses.any?
      poll_responses
        .group_by{ |pr| pr.restaurant }
        .transform_values{ |v| v.count }
        .max_by{|restaurant, vote_count| vote_count }
        .first
    else
      nil
    end
  end

  def closed?
    DateTime.new < end_time
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :validate_admin, only: [:new, :create, :destroy, :update, :edit]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.last
    if PollResponse.where(user: current_user, poll: @poll).exists?
      return redirect_to poll_poll_responses_path(@poll), notice: "Your vote has already been recorded!"
    end
    if DateTime.now > @poll.end_time
      redirect_to poll_poll_responses_path(@poll)
    end
    unless @poll.closed? 
      redirect_to poll_poll_responses_path(@poll)
    end
    @poll_response = @poll.poll_responses.new
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = current_user.polls.create(date: Date.today)
    poll_params[:restaurant_id].each do |restaurant_id|
      @poll.restaurant_polls.find_or_create_by(restaurant_id: restaurant_id)
    end
    render json: @poll
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:restaurant_id => [])
    end

    def validate_admin
      redirect_to users_path unless current_user.admin?
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2 class="text-center">Make a list of restaurants for your peers to vote on!</h2>
      <%= bootstrap_form_with(model: poll) do |f| %>

          <%#= f.text_field :restaurant, 
                            autofocus: true, 
                            class: 'form-control', 
                            placeholder: 'restaurant' %>

        <%= f.submit "Create Poll", class: 'form-control btn btn-primary' %>
      <% end %>            
    </div>
  </div> 
</div>

app/views/polls/_restaurant_vote.html.erb
<%= form_tag(root_path, method: "post") do %>
  <%= radio_button_tag(:restaurant, restaurant.id) %>
  <%= label_tag(:restaurant, restaurant.name)%>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hi, <%= current_user.name %>.</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to 'Show', poll %></td>
        <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poll', new_poll_path, class:"btn btn-primary" %>

app/views/polls/new.html.erb
<%#= render 'form', poll: @poll %>

<%= image_tag 'WhereTo_Logo.svg', class:"poll-logo animated fadeIn delay-1s" %>
<%= react_component "Restaurants" %>

<%#= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<div class="col-md-12">
<h3 class="vote-caption">Where to? Cast your vote below!</h3>
  <%= form_with(model: [@poll, @poll_response]) do |form| %>
    <% @poll.restaurants.each do |restaurant|%>
      <div class="btn-group form-container" data-toggle="buttons">
        <%= form.label(restaurant.name) do %>
          <div class="venue-list">
            <span class="poll-venue-name"><%= restaurant.name %></span>
            <%= form.radio_button(:restaurant_id, restaurant.id, checked: false, class:"form-radio") %>
          </div>
        <% end %>
      </div>
      <hr class="vote-hr">
    <% end %>
    <div class="vote-submit">
      <%= form.submit "Vote!", class: "btn btn-outline-secondary waves-effect vote-button" %>
    </div>
  <% end %>
</div>