config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'pages#index'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users

  resources :restaurants

  resources :polls do
    resources :poll_responses, only: [:create, :index]
    resources :orders, only: [:create, :index, :show]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :name, presence: true
  belongs_to :restaurant
  has_many :restaurant_polls
  has_many :polls, :through => :restaurant_polls
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :dish
  belongs_to :poll

  validates :user_id, uniqueness: { scope: :poll_id }
end

app/models/poll.rb
class Poll < ApplicationRecord
  before_create :set_poll_end_time

  belongs_to :user
  has_many :restaurant_polls, dependent: :destroy
  has_many :restaurants, :through => :restaurant_polls
  has_many :dishes, :through => :restaurant_polls
  has_many :poll_responses, dependent: :destroy
  has_many :orders

  def set_poll_end_time
    self.end_time = DateTime.now + 90.seconds
  end

  def winner
    if closed? && poll_responses.any?
      poll_responses
        .group_by{ |pr| pr.restaurant }
        .transform_values{ |v| v.count }
        .max_by{|restaurant, vote_count| vote_count }
        .first
    else
      nil
    end
  end

  def closed?
    DateTime.new < end_time
  end
end

app/models/poll_response.rb
class PollResponse < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  belongs_to :poll

  validates :user_id, uniqueness: { scope: :poll_id, message: "your vote has already been recorded" }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :city, :state, :zip, presence: true
  has_many :dishes
  has_many :restaurant_polls
  has_many :polls, :through => :restaurant_polls

  def votes_in(poll)
    poll.poll_responses.where(restaurant_id: id).count
  end
end

app/models/restaurant_poll.rb
class RestaurantPoll < ApplicationRecord
  belongs_to :poll
  belongs_to :restaurant
  belongs_to :dish, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :polls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource_or_scope)
    if current_user.admin?
      new_poll_path
    else
      Poll.exists?(Poll.last.end_time > DateTime.now) ? Poll.last : user_path(@user)
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.fetch(:dish, {})
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_poll

  def create
    @order = @poll.orders.new(order_params)
    @order.user = current_user
    if @order.save
      redirect_to [@poll, @order], notice: "Your order will be coming soon"
    else
      redirect_to [@poll, @order], notice: "You already ordered"
    end
  end

  def index
    @orders   = @poll.orders.joins(:dish)
    @summary  = @poll.orders
                  .group_by{|o| o.dish}
                  .map{|dish, orders| [dish.name, orders.count]}
                  .to_h
  end

  def show
    @order = @poll.orders.find(params[:id])
  end

  private

  def set_poll
    @poll = Poll.find(params[:poll_id])
  end

  def order_params
    params.require(:order).permit(:dish_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :validate_admin, only: [:new, :create, :destroy, :update, :edit]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.last
    if PollResponse.where(user: current_user, poll: @poll).exists?
      return redirect_to poll_poll_responses_path(@poll), notice: "Your vote has already been recorded!"
    end
    if DateTime.now > @poll.end_time
      redirect_to poll_poll_responses_path(@poll)
    end
    unless @poll.closed? 
      redirect_to poll_poll_responses_path(@poll)
    end
    @poll_response = @poll.poll_responses.new
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = current_user.polls.create(date: Date.today)
    poll_params[:restaurant_id].each do |restaurant_id|
      @poll.restaurant_polls.find_or_create_by(restaurant_id: restaurant_id)
    end
    render json: @poll
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:restaurant_id => [])
    end

    def validate_admin
      redirect_to users_path unless current_user.admin?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer pt-4">
  <div class="text-center text-md-right">
    <div class="row">
      <div class="col-md-3 mt-md-0 mt-6">

        <p>Find us at: </p>
          <a type="button" class="btn-floating btn-fb btn-sm">
            <i class="fa fa-facebook"></i>
          </a>
          <a type="button" class="btn-floating btn-tw btn-sm">
            <i class="fa fa-twitter"></i>
          </a>
          <a type="button" class="btn-floating btn-li btn-sm">
            <i class="fa fa-linkedin"></i>
          </a>
          <a type="button" class="btn-floating btn-git btn-sm">
            <i class="fa fa-github"></i>
          </a>

      </div>
<hr class="clearfix w-100 d-md-none pb-3">
<p>Created by William Kontos, Adam Wachsberg, Adam Noah and Richard Crismond of Wyncode Academy</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="row">

      <!-- Elements visible all the time -->
      <div class="col-sm-6">
        <%= render 'layouts/navigation/header' %>
      </div>

      <!-- Elements collapses on smaller devices -->
      <div class="col-sm-6">
        <%= render 'layouts/navigation/collapsible_elements' %>
      </div>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhereTo?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.14/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'app-bundle' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <% if user_signed_in? %>
      <li class="dropdown pc-menu">
        <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span id="user-name"><%= current_user.name %></span>
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

      <li class="mobile-menu">
        <%= link_to 'Edit Profile', edit_user_registration_path %>
      </li>
      <li class="mobile-menu">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

    <% else # user not signed in %>
      <li class="home-page"><%= link_to 'Login', login_path %></li>
      <li class="home-page"><%= link_to 'Signup', signup_path %></li>
    <% end  %>
  </ul>
</div>

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'WhereTo?', 
      current_user && current_user.admin? ? new_poll_path : @poll, 
      class: 'navbar-brand' %>
</div>

app/views/pages/index.html.erb
<h1>WhereTo?</h1>